## Inspection of the compressing data

In [31]:
import bz2
import pandas as pd
import re
import numpy as np

In [ ]:
# reddit_comments_2019_02.csv and reddit_posts_2019_02.csv.gz are a sample of 1.000.000 data each dowloaded
# ordering created_utc as the original ds is ordered by subreddit.

In [9]:
comments_df = pd.read_csv('/Users/giuliagalli/Documents/GitHub/TFM/reddit/00_data/reddit_comments_2019_02.csv.gz', compression='gzip', 
                                 header=0, sep=',', quotechar='"')

In [15]:
comments_df.shape

(1000000, 3)

In [10]:
comments_df.head(10)

,created_utc,body,subreddit
0,1548979200,"Nah I think that’s the biggest one, I’m in it ...",RocketLeagueExchange
1,1548979200,Checking in,pornfree
2,1548979200,traditionally you have a 2nd tortilla undernea...,Austin
3,1548979200,Yeah it can get bad. Muting earlier than later...,Smite
4,1548979200,Sorry,FortNiteBR
5,1548979200,Just ran a all boarding fleet and did decently...,BFGArmada
6,1548979200,They’re really letting Donger down,USLPRO
7,1548979200,All my mail is for the previous 6 tenants...so...,chicago
8,1548979200,It's okay! The only way we can find out the an...,fursuit
9,1548979200,It because when you first start playing your m...,gaming

In [13]:
comments_df.describe()

        created_utc
count  1.000000e+06
mean   1.548988e+09
std    5.301421e+03
min    1.548979e+09
25%    1.548984e+09
50%    1.548988e+09
75%    1.548993e+09
max    1.548998e+09

In [11]:
posts_df = pd.read_csv('/Users/giuliagalli/Documents/GitHub/TFM/reddit/00_data/reddit_posts_2019_02.csv.gz', compression='gzip', 
                                 header=0, sep=',', quotechar='"')

In [16]:
posts_df.shape

(1000000, 4)

In [12]:
posts_df.head(10)

,created_utc,title,selftext,subreddit
0,1548979200,Xiaomi President Shows Off Its Folding Phone,NaN,businesstalkdaily
1,1548979200,[GAME THREAD] Our Milwaukee Bucks (36-13) visi...,#r/MkeBucks ANNOUNCEMENTS AND REMINDERS\n\n-\t...,MkeBucks
2,1548979200,Wearing only a thong and a smile ;D,NaN,palegirls
3,1548979200,01-31 23:59 - 'Pee walls in the boys bathrooms...,'''\n\nNow this might sound really strange but...,removalbot
4,1548979200,Wtf?! Its time already.. Where are the leaks/p...,The event should have started by now so where ...,IdleHeroes
5,1548979200,Skrill removed all of bangarang from Apple Mus...,[deleted],EDM
6,1548979200,[WIP] Heeeeeeeeere's Johnny!,NaN,CrossStitch
7,1548979200,Orang defend,NaN,TheGreenArmy
8,1548979200,My stocks,NaN,logodesign
9,1548979201,What location are you most likely to be killed...,[deleted],AskReddit

In [14]:
posts_df.describe()

        created_utc
count  1.000000e+06
mean   1.549062e+09
std    4.796624e+04
min    1.548979e+09
25%    1.549025e+09
50%    1.549059e+09
75%    1.549105e+09
max    1.549144e+09

In [18]:
comments_df.body.sample(7)

603821     Holy shit, what a stupid and offensive picture.
63376     Ugh, I hate defending the lakers but this is j...
39234     I traded a 2nd round 2019 pick for Eli Fn Mann...
35609     Raised on baseball from birth, so I got the Me...
542952                     Hi again. What's the new number?
246484                                          21 days old
93406                              Mr Bean.\n\n&amp;#x200B;
Name: body, dtype: object

In [20]:
posts_df.title.sample(10)

561716    EXECUTIVE CHEF - Morgantown, WV - Compass Grou...
503896                                           Butt Bread
751076                                            A glitch?
559180    [TOMT][Reddit Post] imgur album with grim phot...
802451                                      Thomas Mcdonell
345637            Thoughts on Prince Lothric fight? Spoiler
704341    Should I Invest In A Foreclosed Home In GA Fro...
209984    So not many people play Sylas I guess, 'cause ...
883056            What do you call a Muslim in a UPS truck?
886753    LIVE ThreaD [02:30 ET]! Garcia v/s@.Cheeseman ...
Name: title, dtype: object

In [21]:
posts_df.selftext.sample(10)

530891    Is a Naga +''Something'' a solution to the AOE...
844126                                                  NaN
662098                                            [removed]
811546                                                  NaN
338327                                                  NaN
235047    \^&amp;%$ {{ bussness problem solution }}\*&am...
578023    [Game Thread] #NFL: New England Patriots vs Lo...
433164                                                  NaN
99576                                                   NaN
845612                                            [deleted]
Name: selftext, dtype: object

In [ ]:
# Let's see if whe HTML tags in our comments and posts

In [35]:
test = posts_df.title.compile(r'<[^>]+>')
test.sample(10)

AttributeError: 'Series' object has no attribute 'compile'

In [ ]:
# Let's see how many nullwe have in our comments and posts

In [33]:
# we have NaN values on the body of the subreddit that we can drop
comments_df.isnull().sum()

created_utc    0
body           7
subreddit      0
dtype: int64

In [41]:
# we have a lot of NaN values on the self text but we will keep it because the of the title not NaN
# we have 8 NaN on the title where we can check if have values on the selftext
posts_df.isnull().sum()

created_utc         0
title               8
selftext       535906
subreddit           0
dtype: int64

In [42]:
# where the title is NaN, also the selftext is NaN so we can drop them
posts_df[posts_df["title"].isnull()]

        created_utc title selftext         subreddit
487442   1549057095   NaN      NaN    u_hannaonprime
487870   1549057159   NaN      NaN    u_hannaonprime
578866   1549070350   NaN      NaN           u_honda
579490   1549070451   NaN      NaN           u_honda
592231   1549072492   NaN      NaN    u_hannaonprime
592442   1549072521   NaN      NaN    u_hannaonprime
837726   1549121657   NaN      NaN   ProgrammerHumor
896334   1549129709   NaN      NaN  Anime_For_Otakus

In [43]:
# let's drop into comments ds
test = comments_df.dropna(axis=0)

In [45]:
test.shape

(999993, 3)

In [46]:
comments_df_clear = comments_df.dropna(axis=0)

In [61]:
# we can check it
comments_df_clear.isnull().sum()

created_utc    0
body           0
subreddit      0
dtype: int64

In [56]:
test = posts_df.dropna(subset=['title'])

In [57]:
test.shape

(999992, 4)

In [58]:
# let's drop into posts ds only the 8 raws with NaN values in title and selftext
posts_df_clear = posts_df.dropna(subset=['title'])

In [60]:
# we can check it
posts_df_clear.isnull().sum()

created_utc         0
title               0
selftext       535898
subreddit           0
dtype: int64

In [101]:
posts_df_clear.title.map(lambda x: len(x)).max()

938

In [102]:
posts_df_clear['lengh_title']= posts_df_clear.title.map(lambda x: len(x))

/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [103]:
posts_df_clear.sort_values(by=['lengh_title'], ascending=False)

,created_utc,title,selftext,subreddit,lengh,lengh_title
68201,1548989072,Spurs coach Gregg Popovich was asked about how...,NaN,u_LumpyObject,938,938
574899,1549069731,do u hate ur life !! �������������������������...,NaN,NatureIsFuckingLit,517,517
673962,1549086507,asdasd�� �� �� �� �� �� �� �� �� ���� �� �� ��...,NaN,Community_Demo,455,455
528873,1549062786,L train you're dragon[gggg&amp;gggggy&amp;gygg...,[deleted],ChoosingBeggars,364,364
907434,1549131205,WATCH NFL FINAL MATCH LIVE@@&gt;Patriots vs Ra...,[removed],CowboysRamsLiveTv,363,363
908474,1549131343,[[ !!!~&gt;&gt; NFL TV THREAD &lt;&lt;!!! ]] P...,[removed],CowboysRamsLiveTv,360,360
908831,1549131389,rEDDIT[[**WATCH --- &gt; Patriots vs Rams Live...,[removed],CowboysRamsLiveTv,352,352
909716,1549131508,[[ ~@#&gt; Patriots vs Rams Live S?t?r?e?a?m? ...,[removed],CowboysRamsLiveTv,348,348
908238,1549131314,2019 SUPER BOWL LIII Live-#@$^&gt; Patriots vs...,[removed],CowboysRamsLiveTv,340,340
907232,1549131178,%:::&gt;WaTcH@ Patriots vs Rams Live %:::&gt;s...,[removed],CowboysRamsLiveTv,338,338
124734,1548998103,Can someone who doesn't know a lot about taran...,[removed],AskReddit,332,332
997153,1549143302,[-LIVE-REDDIT] Super Bowl 2019 Live &lt;@&gt;S...,\n\n\[-LIVE-REDDIT\] Super Bowl 2019 Live &lt...,SuperBowlZoneTv,332,332
907799,1549131252,##&gt;||--4K LIVE--||&lt;&lt;#@-- Patriots vs ...,[removed],CowboysRamsLiveTv,329,329
736278,1549101481,The largest and most faithful online fashion s...,The largest and most faithful online fashion s...,u_jaliltangail,326,326
542594,1549064785,Ever searched Mount Celeste on google maps? Th...,NaN,celestegame,325,325
819490,1549118890,"‘Go be a sailor, youll travel the world &amp; ...",[removed],WritingPrompts,324,324
756610,1549106437,Ufxfduvh tcaw78cudhynhggtvhivubvyni y ub gvy f...,NaN,teenagersnew,322,322
909328,1549131449,ReDDIT[[ %**WaTCh**% ]] ]] New England Patriot...,[removed],CowboysRamsLiveTv,322,322
909094,1549131419,[[ !!!&gt;&gt;Reddit&lt;&lt;!! ]] Patriots vs ...,[removed],CowboysRamsLiveTv,322,322
621507,1549077116,Learn new skills in Southern New England: Gard...,[deleted],providence,316,316
513366,1549060620,Learn new skills in Southern New England: Gard...,NaN,EcoNewsNetwork,316,316
75119,1548990097,Learn new skills in Southern New England: Gard...,[deleted],SquareFootGardening,316,316
70806,1548989450,Learn new skills in Southern New England: Gard...,[deleted],Green,316,316
73894,1548989908,Learn new skills in Southern New England: Gard...,[deleted],Thrifty,316,316
562665,1549067786,Learn new skills in Southern New England: Gard...,[deleted],massachusetts,316,316
72382,1548989685,Learn new skills in Southern New England: Gard...,[deleted],pickling,316,316
70206,1548989358,Learn new skills in Southern New England: Gard...,[deleted],composting,316,316
611604,1549075492,Learn new skills in Southern New England: Gard...,[deleted],EasternCT,316,316
69358,1548989237,Learn new skills in Southern New England: Gard...,[deleted],maplesyrup,316,316
562323,1549067730,Learn new skills in Southern New England: Gard...,[deleted],Permaculture,316,316
...,...,...,...,...,...,...
472257,1549055066,K,[deleted],u_HououinKyouma999,1,1
761918,1549107673,J,[deleted],animalkingdom,1,1
528298,1549062700,E,NaN,YellowOnlineUnion,1,1
643331,1549080774,F,NaN,teenagersnew,1,1
234827,1549022153,~,NaN,DSRRed,1,1
517643,1549061213,m,[deleted],rule34gay,1,1
597416,1549073243,G,[removed],SkincareAddiction,1,1
119804,1548997280,L,Next week :(,liluzivert,1,1
856963,1549124357,:,NaN,u_Toofreakinhott,1,1
174996,1549008090,z,NaN,FVGmemes,1,1
386343,1549044030,✌,NaN,selfie,1,1
855404,1549124138,:,NaN,u_Toofreakinhott,1,1
326530,1549036522,.,[deleted],FORTnITE,1,1
840322,1549122034,A,[deleted],u_ReasoneWhy,1,1
499890,1549058781,.,NaN,memesofthedank,1,1
907086,1549131159,.,NaN,funny,1,1
958938,1549138054,.,NaN,chapotraphouse2,1,1
185059,1549010547,.,NaN,feet,1,1
165157,1549005928,.,[deleted],ExNoContact,1,1
45807,1548985677,e,[deleted],Rainbow6,1,1
140674,1549001033,H,[removed],u_sblx18,1,1
971802,1549139809,J,NaN,SuggestALaptop,1,1
238449,1549022811,~,NaN,DSRRed,1,1
643347,1549080778,F,NaN,Animemes,1,1
322500,1549035983,?,NaN,teenagers,1,1
729780,1549099787,F,NaN,2meirl4meirl,1,1
840330,1549122035,E,NaN,YellowOnlineUnion,1,1
908600,1549131359,A,NaN,justa,1,1
409757,1549046980,?,NaN,u_F3malef0rms,1,1
476240,1549055582,.,NaN,u_Schoopanda,1,1

In [68]:
posts_df_clear.title.map(lambda x: len(x)).min()

1

In [82]:
comments_df_clear.body.map(lambda x: len(x)).max()

10088

In [83]:
comments_df_clear.body.map(lambda x: len(x)).min()

1

In [ ]:
# posts con min=1 eliminar los que no tengan selftext
# hacer el max de Comments
# comments con leng=1 eliminarlos porque no aportan nada
# ver como hacer para los caracteres raros
# contestar al profe